services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres_dev
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres_data:
