services:
  db:
    image: mysql:8.0.29-oracle
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
    ports:
      - "127.0.0.1:13306:13306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
