services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: --replSet rs0
    restart: on-failure
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=dev
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  mongo-init:
    image: mongo
    restart: unless-stopped
    depends_on:
      - mongodb
    command: >
      sh -c "sleep 5; mongosh --host mongodb:27017 --eval '
      rs.initiate( {
        _id : \"rs0\",
        members: [
          { _id: 0, host: \"mongodb:27017\" }
        ]
      })
      '"

networks:
  default:
    name: mongoCluster

volumes:
  mongodb_data:
