services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=dev

volumes:
  mongodb_data:
