services:
  redis:
    image: redis:6.2-alpine
    # restart: always
    ports:
      - "127.0.0.1:6379:6379"
    command: >
      --port 6379
    #   # --include /usr/local/etc/redis/redis.conf
    #   # --requirepass testpass
    #   --port 6379
    # environment:
    # - REDIS_PASSWORD=testpass
    # volumes:
    # - ./redis.conf:/usr/local/etc/redis/redis.conf
